[package]
name = "vercre-did"
description = """
Decentralized Identifier (DID) utilities for Rust. See features for implemented DID methods and key
management or use core functionality to implement your own.
"""
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# [lib]
# name = "vercre_did"
# crate-type = ["cdylib", "rlib"]

[dependencies]
did-core.workspace = true
azure-kv = { workspace = true, optional = true }
did-ion = { workspace = true, optional = true }
did-jwk = { workspace = true, optional = true }
did-web = { workspace = true, optional = true }
keyring = { workspace = true, optional = true }

[features]
azure-kv = ["dep:azure-kv"] # Azure Key Vault as a key ring and signer
did-ion = ["dep:did-ion"] # did:ion DID method
did-jwk = [
    "keyring",
    "dep:did-jwk",
    "dep:keyring",
] # did:jwk DID method. Uses ephemeral key ring and signer
did-web = ["dep:did-web"] # did:web DID method
keyring = ["dep:keyring"] # Ephemeral key ring and signer

[workspace]
resolver = "2"
members = ["crates/*", "examples/*"]

[workspace.package]
authors = ["Vercre"]
categories = [
    "decentralized identity",
    "did",
    "privacy",
    "security",
    "verifiable credentials",
]
edition = "2021"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://vercre.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vercre/vercre"
rust-version = "1.80"
version = "0.1.0"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
serde = { version = "1.0.195", default-features = false, features = [
    "derive",
    "std",
] }
serde_json = { version = "1.0.111", default-features = false, features = [
    "alloc",
] }
tracing = "0.1.40"
azure-kv = { path = "crates/azure-kv" }
did-core = { path = "crates/did-core" }
did-ion = { path = "crates/did-ion" }
did-jwk = { path = "crates/did-jwk" }
did-web = { path = "crates/did-web" }
keyring = { path = "crates/keyring" }
