[package]
resolver = "2"
authors = ["Credibil"]
name = "credibil-did"
description = """
Decentralized Identifier (DID) utilities for Rust. See features for implemented DID methods and key
management or use core functionality to implement your own.
"""
# categories = ["decentralized identity", "did"]
edition = "2024"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://credibil.io"
keywords = ["decentralized", "identity","did"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/credibil/credibil"
rust-version = "1.85"
version = "0.1.2"

# [lib]
# crate-type = ["cdylib", "rlib"]

# [[example]]
# name = "did-web"

[features]

[lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[dependencies]
anyhow = "1.0.96"
base64ct = { version = "1.6.0", features = ["std"] }
chrono = { version = "0.4.39", features = ["serde"] }
credibil-infosec = "0.1.1"
curve25519-dalek = "4.1.3"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
multibase = "0.9.1"
rand = "0.8.5"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = { version = "1.0.139", features = ["alloc"] }
thiserror = "2.0.11"
url = "2.5.4"

[dev-dependencies]
axum = "0.8.1"
insta = { version = "1.42.1", features = ["filters", "json", "redactions", "yaml"] }
tokio = { version = "1.43.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
