[package]
name = "credibil-identity"
authors.workspace = true
description.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[features]

[dependencies]
anyhow.workspace = true
base64ct.workspace = true
chrono = { version = "0.4.40", features = ["serde"] }
credibil-jose.workspace = true
credibil-ose.workspace = true
multibase.workspace = true
nom = "8.0.0"
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer = "0.3.0"
sha2.workspace = true
url = "2.5.4"
uuid = { version = "1.15.1", features = ["v4"] }

[dev-dependencies]
axum = "0.8.1"
kms.workspace = true
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
serde-jsonlines = "0.7.0"

[workspace]
members = [
    "crates/kms",
    "examples/webvh",
]
resolver = "2"

[workspace.package]
authors = ["Credibil"]
description = """
Decentralized Identifier (DID) and X509 utilities for Rust. See features for implemented DID methods and key
management or use core functionality to implement your own.
"""
edition = "2024"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://credibil.io"
keywords = ["decentralized", "identity","did"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/credibil/identity"
rust-version = "1.86"
version = "0.1.2"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.96"
base64ct = { version = "1.6.0", features = ["std"] }
credibil-identity = { path = "." } 
credibil-jose = { git = "https://github.com/credibil/jose.git", branch = "ose" }
credibil-ose = { git = "https://github.com/credibil/ose.git" }
kms = { path = "crates/kms" }
multibase = "0.9.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = { version = "1.0.139", features = ["alloc"] }
sha2 = "0.10.8"
test-kms = { git = "https://github.com/credibil/ose.git" }

[patch.crates-io]
# credibil-jose = { path = "../jose" }
# credibil-jose = { git = "https://github.com/credibil/jose.git" }

