[package]
name = "vercre-did"
description = """
Decentralized Identifier (DID) utilities for Rust. See features for implemented DID methods and key
management or use core functionality to implement your own.
"""
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# [lib]
# crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
base64ct.workspace = true
chrono.workspace = true
curve25519-dalek = "4.1.3"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
multibase = "0.9"
rand = "0.8.5"
regex = "1.11.0"
serde.workspace = true
serde_json.workspace = true
thiserror = "1.0"
url = "2.5.2"
# vercre-core.workspace = true
vercre-infosec.workspace = true

[dev-dependencies]
insta = { version = "1.40.0", features = ["filters", "json", "redactions", "yaml"] }
tokio.workspace = true

# did-core.workspace = true
# azure-kv = { workspace = true, optional = true }
# did-ion = { workspace = true, optional = true }
# did-jwk = { workspace = true, optional = true }
# did-web = { workspace = true, optional = true }
# keyring = { workspace = true, optional = true }

[features]
azure-kv = [] # = ["dep:azure-kv"] 
did-ion = []  # = ["dep:did-ion"]
did-jwk = []  # = [ "keyring", "dep:did-jwk", "dep:keyring"] 
did-web = []  # = ["dep:did-web"] 
keyring = []  # = ["dep:keyring"]

[workspace]
resolver = "2"
members = ["crates/*", "examples/*"]

[workspace.package]
authors = ["Vercre"]
categories = [
    "decentralized identity",
    "did",
    "privacy",
    "security",
    "verifiable credentials",
]
edition = "2021"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://vercre.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vercre/vercre"
rust-version = "1.80"
version = "0.1.0"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.89"
azure-kv = { path = "crates/azure-kv" }
base64ct = { version = "1.6.0", features = ["std"] }
chrono = { version = "0.4.38", features = ["serde"] }
did-core = { path = "crates/did-core" }
did-ion = { path = "crates/did-ion" }
did-jwk = { path = "crates/did-jwk" }
did-web = { path = "crates/did-web" }
keyring = { path = "crates/keyring" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["alloc"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
vercre-infosec = { git = "https://github.com/vercre/infosec.git" }
