[package]
name = "vercre-did"
version = "0.1.0"
authors = ["Credibil"]
description = """
Decentralized Identifier (DID) utilities for Rust. See features for implemented DID methods and key
management or use core functionality to implement your own.
"""
categories = ["decentralized identity", "privacy", "security", "verifiable credentials"]
edition = "2021"
license = "MIT or Apache-2.0"
repository = "https://github.com/vercre/vercre-did"

[lib]
name = "vercre_did"
crate-type = ["cdylib", "rlib"]

[dependencies]
vercre-azurekv = { path = "vercre-azurekv", optional = true }
vercre-didcore = { path = "vercre-didcore" }
vercre-didion = { path = "vercre-didion", optional = true }
vercre-didjwk = { path = "vercre-didjwk", optional = true }
vercre-didweb = { path = "vercre-didweb", optional = true }
vercre-ephemeral-keyring = { path = "vercre-ephemeral-keyring", optional = true }

[features]
azure-kv = ["dep:vercre-azurekv"] # Azure Key Vault as a key ring and signer
didion = ["dep:vercre-didion"] # did:ion DID method
didjwk = ["dep:vercre-didjwk", "dep:vercre-ephemeral-keyring"] # did:jwk DID method. Uses ephemeral key ring and signer
didweb = ["dep:vercre-didweb"] # did:web DID method
ephemeral-keyring = ["dep:vercre-ephemeral-keyring"] # Ephemeral key ring and signer

[workspace]
resolver = "2"
members = [
    "vercre-azurekv",
    "vercre-didcore",
    "vercre-didion",
    "vercre-didjwk",
    "vercre-didweb",
    "vercre-ephemeral-keyring",
    "examples/ion",
    "examples/web",
    "examples/universal-resolver",
]

[workspace.dependencies]
serde = { version = "1.0.195", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.111", default-features = false, features = ["alloc"] }
tracing = "0.1.40"
