[package]
name = "universal-resolver"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
reqwest = { version = "0.11.23", features = ["json"] }
tokio = { version = "1.35.1", features = ["full"] }
vercre-did = { path = "../.." }
