[package]
name = "universal-resolver"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
did-core.workspace = true
reqwest = { version = "0.12.8", features = ["json"] }
tokio = { version = "1.40.0", features = ["full"] }
