[package]
name = "ion"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
vercre-did = { path = "../..", features = ["did-ion"] }
