[package]
name = "jwk"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
did-core.workspace = true
did-jwk.workspace = true
keyring.workspace = true
tokio = { version = "1.40.0", features = ["full"] }
vercre-did = { path = "../..", features = ["did-jwk"] }
